# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-02 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('level', models.CharField(max_length=32)),
                ('external_id', models.CharField(max_length=64, null=True)),
                ('msg', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('url', models.URLField(null=True)),
                ('release', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('maintainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Person')),
                ('properties', models.ManyToManyField(to='report.Property')),
                ('tags', models.ManyToManyField(to='report.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('name', models.CharField(max_length=64)),
                ('sources', models.ManyToManyField(to='report.Source')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Task')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together=set([('name', 'release')]),
        ),
        migrations.AddField(
            model_name='log',
            name='external_id_prop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Property'),
        ),
        migrations.AddField(
            model_name='log',
            name='task_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.TaskRun'),
        ),
        migrations.AddField(
            model_name='log',
            name='wdid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Item'),
        ),
        migrations.AlterUniqueTogether(
            name='taskrun',
            unique_together=set([('task', 'timestamp')]),
        ),
    ]
