# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-03 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_source_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='timestamp',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together=set([('name', 'release', 'timestamp')]),
        ),
    ]
