# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20161103_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='msg_type',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
